name: deploy

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true
      PYPI_TOKEN:
        required: false
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    concurrency:
      group: deploy
    runs-on: ubuntu-latest

    steps:
      # existing steps...

      - name: Release
        shell: bash
        run: poetry run semantic-release
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}